### ISSUE TITLE
IT DOESN'T WORK!! JUST MAKE IT WORK OK

### ISSUE THREAD

**Issue by BrydenIsNotSmart** [BrydenIsNotSmart/VitalList#1]
IT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OKIT DOESN'T WORK!! JUST MAKE IT WORK OK

**Comment by sldless** [comment]
Thanks fixed the issue.
